// packages/admin-vue3/src/ui/FormSelect.vue
<template>
    <div>
        <field-title v-bind="$attrs" />
        <form-select v-bind="$attrs" />
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { FormSelect, FieldTitle } from '@macramejs/macrame-vue3';

export default defineComponent({
    components: { FormSelect, FieldTitle },
});
</script>

// packages/admin-react/src/ui/FormSelect.tsx
import { FieldTitle } from '@macramejs/macrame-react';
import { FormSelect as BaseFormSelect } from '@macramejs/macrame-react';

const FormSelect = function (props) {
    return (
        <div>
            <FieldTitle {...props} />
            <BaseFormSelect {...props} />
        </div>
    );
};

export default FormSelect;
