// packages/admin-react/src/ui/Card.tsx
import classNames from 'classnames';
import getVariant from './props/variant';
import getSize from './props/size';

type CardProps = {
    as?: string,
    [k: string]: any
}

const Card = function({ 
    as = 'div', 
    ...props
}: CardProps, context) {
    const Tag = as as keyof JSX.IntrinsicElements;
    const variant = getVariant(props, { DEFAULT: 'white' });
    const size = getSize(props, { only: ['sm', 'md'] });

    return (
        <Tag className={classNames({
            'rounded-sm p-6': true,
            'bg-white shadow': variant == 'white',
            'bg-gray-300': variant == 'gray',
            'p-12': size == 'md',
            'p-8': size == 'sm',
            [props.className]: true
        })}>
            {props.children}
        </Tag>
    );
}

export default Card;

// packages/admin-vue3/src/ui/Card.vue
<template>
    <component
        :is="as"
        class="rounded-sm"
        :class="{
            'bg-white shadow': variant_ == 'white',
            'bg-gray-300': variant_ == 'gray',
            'p-12': size_ == 'md',
            'p-8': size_ == 'sm',
        }"
    >
        <slot />
    </component>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue';
import { getVariant, variants } from './props/variant';
import { getSize, sizes } from './props/size';

export default defineComponent({
    props: {
        as: {
            type: String,
            default: 'div',
        },
        variant: variants.variant,
        white: {
            type: Boolean,
            default: false,
        },
        gray: variants.gray,
        size: sizes.size,
        sm: sizes.sm,
        md: sizes.md,
    },
    setup(props, { attrs }) {
        let variant_ = getVariant(props, { DEFAULT: 'white' });
        let size_ = getSize(props, { only: ['sm', 'md'] });

        return { variant_, size_ };
    },
});
</script>

<style></style>
