// packages/admin-react/src/components/FormTextarea.tsx
import { FieldTitle } from '@macramejs/macrame-react';
import { FormTextarea as BaseFormTextarea } from '@macramejs/macrame-react';

const FormTextarea = function (props) {
    return (
        <div>
            <FieldTitle {...props} />
            <BaseFormTextarea {...props} />
        </div>
    );
};

export default FormTextarea;

// packages/admin-vue3/src/ui/FormTextarea.vue
<template>
    <div>
        <field-title v-bind="$attrs" />
        <form-textarea v-bind="$attrs" />
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { FormTextarea, FieldTitle } from '@macramejs/macrame-vue3';

export default defineComponent({
    components: { FormTextarea, FieldTitle },
});
</script>
