// packages/admin-react/src/pages/BasePage.tsx
import { Component as ReactComponent } from 'react';
import { Component } from '@macramejs/macrame-react';
import { Component as TComponent } from '@macramejs/macrame';

export default class BasePage extends ReactComponent<{ components: TComponent[] }> {
	render() {
		return (
			<div>
				{this.props.components.map((component, i) => (
					<Component
						key={i}
						name={component.name}
						props={component.props}
					/>
				))}
			</div>
		);
	}
}

// packages/admin-vue3/src/pages/BasePage.vue
<template>
    <div>
        <component
            v-for="(component, index) in components"
            v-bind="component.props"
            :is="component.name"
            :key="index"
        />
    </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from 'vue';
import { Component } from '@macramejs/macrame';
export default defineComponent({
    name: 'BasePage',
    props: {
        components: {
            required: true,
            type: Array as PropType<Component[]>,
        },
    },
});
</script>
