// packages/admin-react/src/ui/FormInput.tsx
import { FieldTitle } from '@macramejs/macrame-react';
import { FormInput as BaseFormInput } from '@macramejs/macrame-react';

const FormInput = function (props) {
    return (
        <div>
            <FieldTitle {...props} />
            <BaseFormInput {...props} />
        </div>
    );
};

export default FormInput;

// themes/empty-vue3/src/ui/FormInput.vue
<template>
    <div>
        <field-title v-bind="$attrs" />
        <form-input v-bind="$attrs" />
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { FormInput, FieldTitle } from '@macramejs/macrame-vue3';

export default defineComponent({
    components: { FormInput, FieldTitle },
});
</script>
